### ISSUE TITLE
Expose positioning of "# Slack Feedback"

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#14]
This is a really nice tool, is there any change you could expose the positioning of the trigger button?

**Comment by markmur** [comment]
I have plans to implement this but not any time soon unfortunately due to a very busy schedule at work. I'll happily accept PRs though if you'd like to look into it. I don't actively use Slack day-to-day so this component is not a priority at the moment.

**Comment by keiranmraine** [comment]
I'll take a look when I get to implementing, happy to contribute.

**Comment by aboutaaron** [comment]
Is this still doable in v2 using the `theme` prop?
