### ISSUE TITLE
Change text of title bar?

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#15]
Could you add the ability to modify the text of the title bar?  Currently 'Send feedback to Slack'.

**Comment by markmur** [comment]
Yep, you can use the `title` prop.

https://github.com/markmur/react-slack-feedback/blob/master/src/SlackFeedback.js#L39

**Comment by keiranmraine** [comment]
Ah great, looks like I can handle #16 in this way too.
