### ISSUE TITLE
Override Slack icon

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#16]
Could you expose the icon (![screen shot 2018-03-29 at 11 15 30](https://user-images.githubusercontent.com/3740323/38083806-98b74ef2-3342-11e8-9e37-fbb2a6270351.png)) so that it can be changed.

Sorry for the separate items, but from what I can see there's nothing that specifically ties the UI to Slack.  Adding these would make this a very flexible tool.  Happy to test.

**Comment by markmur** [comment]
@keiranmraine this has been published in `v1.1.3`.

```js
import Feedback, { SlackIcon } from 'react-slack-feedback';
```
