### ISSUE TITLE
Link emoji to bug/improvement/feature

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#24]
It would be nice if it was possible to set the emoji for each type of feedback option making emoji more like:

```
emoji=':bug:' // preserve existing
emojiDetailed={{bug: ':bug:', feature: ':building_construction:', improvement: 'bulb'}}
```

<img width="167" alt="screen shot 2018-04-20 at 06 40 43" src="https://user-images.githubusercontent.com/3740323/39032516-c9014b6a-4465-11e8-83f9-0460ea00497a.png">

Would you accept a PR for this?

**Comment by markmur** [comment]
The `emoji` prop has since been removed, so I'm going to close this issue.
