### ISSUE TITLE
Webpack build error due to unnecessary .babelrc file in npm package

### ISSUE THREAD

**Issue by MartinSoderholm** [markmur/react-slack-feedback#25]
#### Steps
1. `npm install react-slack-feedback`
2. `npm run build` // webpack build

#### Error
> ReferenceError: Unknown plugin "react-html-attrs" specified in ".../node_modules/react-slack-feedback/**.babelrc**"

#### Fix
Builds with no errors after I remove .babelrc file from package.

Add an .npmignore file to your project and add files not necessary in npm package. For example:
```
src
test
.babelrc
.eslintrc
...
```

**Comment by markmur** [comment]
Fixed in #13
