### ISSUE TITLE
any plans for i18n?

### ISSUE THREAD

**Issue by plamenh** [markmur/react-slack-feedback#27]
Hey there,

Thanks for the awesome plugin. Do you have any plans for i18n support?

Right now it's English only and apart from the button text prop, there's no way to translate in a reliable way.

Have you thought about adding support for i18next, for example?

**Comment by markmur** [comment]
Hey @finkbg, I don't currently use this component much as I don't use Slack but will happily accept pull requests 😃

**Comment by finkbg** [comment]
Ok, @markmur, you got it :) I will submit a pull request once I get it done. 

One more thing - you say 'I don't use Slack', but in reality this component may be used with any service. For example, I don't use the backend portion at all (I forward the requests to a Symfony backend) and this way the feedback may be forwarded to whatever service you wish.

**Comment by markmur** [comment]
True, except the implementation of the response object is intended to be sent to Slack. I thought about changing it to suit more general needs but never found the time. 

Thanks for the PR, I’ll take a look soon.

**Comment by markmur** [comment]
`translations` prop introduced in #13. See [this file](https://github.com/markmur/react-slack-feedback/blob/master/src/translations.json) for translation keys
