### ISSUE TITLE
New slack-app webhooks don't support some options

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#35]
See the info panel at the end of this section for the info about channel, username and icon:

https://api.slack.com/incoming-webhooks#advanced_message_formatting

The emoji can be prepended to the attachments.title as an alternative.

**Comment by markmur** [comment]
Cool, thanks for the heads up @keiranmraine.

I'm quite tempted to remove connection to *slack* in `V2` and make it a UI component for gathering general feedback to be sent anywhere

**Comment by keiranmraine** [comment]
I think that's a sensible idea, although having slack as a key word is beneficial for searching purposes.  We took the example server side code and expanded to optionally send a permanent record into our GitLab issues for tracking purposes.

**Comment by markmur** [comment]
Fixed in #42. `channel` and `username` have been omitted from the payload
