### ISSUE TITLE
close button - difficult to see

### ISSUE THREAD

**Issue by keiranmraine** [markmur/react-slack-feedback#37]
Is there any chance there's an easy way to override the style of the text used for the `close` button?

We find that it is very difficult to see being black on navy.

I had a play with the chrome tools and setting the colour to white while removing:

* font-weight
* text-shadow

Gives a much easier to see  button.

From:
![screen shot 2019-02-15 at 12 15 36](https://user-images.githubusercontent.com/3740323/52856156-86fb3980-311b-11e9-9e39-97ce91cb41f6.png)

to:
![screen shot 2019-02-15 at 12 16 06](https://user-images.githubusercontent.com/3740323/52856161-8a8ec080-311b-11e9-8c67-c8d635480e10.png)

Were running under bootstrap, but I note that the example in the readme has a similar issue.

**Comment by markmur** [comment]
Yep, this will be configurable in v2 through a `theme` prop, which will let you override most of the styles
