### ISSUE TITLE
Not compatible with latest version of React

### ISSUE THREAD

**Issue by jeffjenk** [markmur/react-slack-feedback#5]
Hi Mark,
I recently updated React and I am getting console errors originating from this component:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Its a fairly simple fix, I am happy to submit a pull request if you like?

**Comment by markmur** [comment]
@jeffjenk Sure! That would be great. Thanks for your contributions
