### ISSUE TITLE
Inspiration?

### ISSUE THREAD

**Issue by gajus** [markmur/react-slack-feedback#51]
@markmur The product looks _really_ good. It also feels really familiar. Is this a replica of some sort of a commercial service?

**Comment by markmur** [comment]
Really appreciate the feedback @gajus. I guess it's subconsciously inspired by some of [Intercom](https://www.intercom.com/)'s work 🤔 It was originally built in an effort to get more internal feedback on tools I was working on at the time

**Comment by gajus** [comment]
It looks really good. I have a good use case for this in our internal tools too. Thank you.

**Comment by markmur** [comment]
Great, glad to hear it 👍 Contributions are welcome 😄

**Comment by ivorcummings** [comment]
+1 really good job

**Comment by markmur** [comment]
Thanks @ivorcummings 👍 appreciate it
