### ISSUE TITLE
Invalid css properties

### ISSUE THREAD

**Issue by Rinta01** [markmur/react-slack-feedback#54]
Check lines 169 and 180 of /src/styles.js.
Border property of actually represents border-color, so there's no way to set 'none'.
Since background-color property on line 180 doesn't have a ';' the property can't be set appropriately.

**Comment by markmur** [comment]
PR welcome 🙂

**Comment by markmur** [comment]
You could also just set the value to transparent

**Comment by markmur** [comment]
Closing as there is a current workaround.
