### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by donaldboulton** [markmur/react-slack-feedback#56]
Forked repo
added .env with WEBHOOK_URL=to slack
yarn to install
yarn start
Error
Cannot GET /

**Comment by markmur** [comment]
The server is listening on port 8080

The client is listening on port 1234

Go to http://localhost:1234 to see the component

**Comment by markmur** [comment]
Readme updated: https://github.com/markmur/react-slack-feedback#contributing
