### ISSUE TITLE
Hover slack button is transparent - more likely to break on 3-d party website

### ISSUE THREAD

**Issue by dev-tim** [markmur/react-slack-feedback#62]
Background on hovered button is transparent - more likely to break on 3-d party website. 
I suggest to make it not transparent so slack icon is visible even if cursor is hovered on it.

![image](https://user-images.githubusercontent.com/5173831/60382657-80d07e80-9a66-11e9-996b-1b31988dc617.png)

**Comment by markmur** [comment]
Hey @dev-tim, in what scenario are you seeing this happen?

By default the button is navy, and the hover color is `inherit`, which inherits from the default navy.

**Comment by domhaas** [comment]
@markmur Can reproduce this - I got the same issue.
The outer class ".fprCaL" doesn't have any background-style. So the inheritance comes from somewhere else.
Maybe it has something to do with antd or blueprintjs. I'm currently doing a workaround by overwriting the classes, so it's fine for me.

Thanks for the great work btw!

**Comment by MityaDementiy** [comment]
@markmur, hi! We have the same problem on https://codebattle.hexlet.io/ Transparent button on hover looks strange. It would be great to make button not transparent. Can I help with pr?

**Comment by markmur** [comment]
Hey @MityaDementiy. Sure, PR welcome 👍

**Comment by markmur** [comment]
This was fixed in `react-slack-feedback@2.1.1` - which has been published
