### ISSUE TITLE
Button component customization

### ISSUE THREAD

**Issue by am0nshi** [markmur/react-slack-feedback#85]
Is there any way to customize button, which triggers proper modal? We need to define it into existing style and change placement ?

**Comment by markmur** [comment]
Yeah, you can modify the `theme` parameter:

https://github.com/markmur/react-slack-feedback/blob/f91344ef9c269e3c87bb299a23c0029074c2418b/src/themes/default.js#L38-L50

The `SlackFeedback` component will deep-merge the `theme` prop with the default theme
